package br.com.util.entity;


import java.time.LocalDateTime;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * AcessoHistoricoSenha generated by hbm2java
 */
@Entity
@Table(name ="acesso_historico_senha", schema = "suporte")
@SequenceGenerator(name="seq_hist_senha", sequenceName="suporte.seq_nu_historico_senha",initialValue=1, allocationSize=1)
public class AcessoHistoricoSenha implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="nu_acesso_historico_senha")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_hist_senha")
	private Integer id;

	@NotNull
	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "nu_usuario")
	private AcessoUsuario acessoUsuario;
	
	@Column(name="de_senha_anterior")
	private String senhaAnterior;
	
	@Column(name="dh_troca_senha")
	private LocalDateTime dataHoraTroca;

	public AcessoUsuario getAcessoUsuario() {
		return this.acessoUsuario;
	}

	public void setAcessoUsuario(AcessoUsuario acessoUsuario) {
		this.acessoUsuario = acessoUsuario;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataHoraTroca == null) ? 0 : dataHoraTroca.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((senhaAnterior == null) ? 0 : senhaAnterior.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AcessoHistoricoSenha other = (AcessoHistoricoSenha) obj;
		if (dataHoraTroca == null) {
			if (other.dataHoraTroca != null)
				return false;
		} else if (!dataHoraTroca.equals(other.dataHoraTroca))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (senhaAnterior == null) {
			if (other.senhaAnterior != null)
				return false;
		} else if (!senhaAnterior.equals(other.senhaAnterior))
			return false;
		return true;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSenhaAnterior() {
		return senhaAnterior;
	}

	public void setSenhaAnterior(String senhaAnterior) {
		this.senhaAnterior = senhaAnterior;
	}

	public LocalDateTime getDataHoraTroca() {
		return dataHoraTroca;
	}

	public void setDataHoraTroca(LocalDateTime dataHoraTroca) {
		this.dataHoraTroca = dataHoraTroca;
	}
	
}
